name: Deploy React App to Hostinger VPS

on:
  push:
    branches:
      - main # Or whatever branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Or your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.VPS_TARGET_DIRECTORY }}
            # Remove old build files (optional, but good for clean deployments)
            rm -rf *
            # Copy new build files
            cp -r /home/runner/work/${{ github.repository }}/${{ github.repository }}/build/* . # Adjust path based on your build folder location
            # Restart Nginx (if necessary, or just rely on it serving static files)
            sudo systemctl restart nginx
